name: Run PHP Unit Tests

on: [pull_request]

jobs:
  phpunit-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Install Subversion (svn)
        run: sudo apt-get update && sudo apt-get install -y subversion

      - name: Download WP testing suite
        run: |
          echo y | bash ./bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 6.8.1

      - name: Run PHPUnit tests
        env:
          WP_TESTS_DB_NAME: wordpress_test
          WP_TESTS_DB_USER: root
          WP_TESTS_DB_PASS: root
          WP_TESTS_DB_HOST: 127.0.0.1
        run: vendor/bin/phpunit --configuration phpunit.xml

      - name: Comment on PR if tests fail
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const runUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID}`;
            const commentBody = `
            ❌ **PHPUnit Tests Failed**

            You can check the full details here: [Workflow Run](${runUrl})

            Please review and fix the errors.
            `;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: commentBody
            });